'Avatar Addition':
  - '**/data.json'

'Avatar Detection':
  - '**/data_schema.json'
  - '**/Scripts/Detection/**/*'

'Flight Physics':
  - '**/Scripts/Flight/**/*'

'UI':
  - '**/Scripts/UI/**/*'

'documentation':
  - 'docs/**/*'
